<script setup>
// Eight refinements of the chosen T7 structure. Shared data/mechanics, different overview,
// plot, inspector and control treatments. No winning visual treatment has been chosen.
import {computed,defineAsyncComponent,nextTick,onMounted,onUnmounted,provide,reactive,ref,watch} from 'vue';
import {sources,recordsAll,DURATION,INCIDENT,designs} from './model';import LensChat from './LensChat.vue';import {Search,ChevronLeft,ChevronRight,Info,X} from 'lucide-vue-next';
const components={L1:defineAsyncComponent(()=>import('./Lens01.vue')),L2:defineAsyncComponent(()=>import('./Lens02.vue')),L3:defineAsyncComponent(()=>import('./Lens03.vue')),L4:defineAsyncComponent(()=>import('./Lens04.vue')),L5:defineAsyncComponent(()=>import('./Lens05.vue')),L6:defineAsyncComponent(()=>import('./Lens06.vue')),L7:defineAsyncComponent(()=>import('./Lens07.vue')),L8:defineAsyncComponent(()=>import('./Lens08.vue'))};
const initial=new URLSearchParams(location.search).get('variant')?.toUpperCase();
const current=ref(designs.some(d=>d.key===initial)?initial:'L1');const active=computed(()=>designs.find(d=>d.key===current.value));const dev=import.meta.env.DEV;
const state=reactive({start:INCIDENT-60,span:300,selectedId:'EV-106',query:'',target:'',onlyAlerts:false,tags:[],draft:'',messages:[]});
const selected=computed(()=>recordsAll.find(e=>e.id===state.selectedId)||null);
const filtered=computed(()=>{const q=state.query.trim().toLowerCase();return recordsAll.filter(e=>(!state.target||e.target===state.target)&&(!state.onlyAlerts||e.severity!=='normal')&&(!q||[e.id,e.title,e.target,e.raw?.message_id].join(' ').toLowerCase().includes(q)))});
const visible=computed(()=>filtered.value.filter(e=>e.t<state.start+state.span&&(e.end??e.t)>=state.start));
const related=computed(()=>{const e=selected.value;if(!e)return [];return recordsAll.filter(x=>x.id!==e.id&&(e.raw?.message_id?x.raw?.message_id===e.raw.message_id:x.target===e.target&&Math.abs(x.t-e.t)<120))});
const relatedIds=computed(()=>related.value.map(e=>e.id));
function setRange(start,span){state.span=Math.max(30,Math.min(1800,span));state.start=Math.max(0,Math.min(DURATION-state.span,start));const e=selected.value;if(e&&(e.t>=state.start+state.span||(e.end??e.t)<state.start))state.selectedId=null;}
function incident(){setRange(INCIDENT-60,300)}
function select(id,reveal=true){state.selectedId=id;if(reveal)nextTick(()=>{const panel=document.querySelector('.evidence-inspector');if(panel&&panel.getBoundingClientRect().top>innerHeight*.8)window.scrollBy({top:panel.getBoundingClientRect().top-innerHeight*.6,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})});}
function jump(id){const e=recordsAll.find(e=>e.id===id);if(!e)return;state.query='';state.target='';state.onlyAlerts=false;setRange(e.t-60,300);select(id,false);nextTick(()=>document.querySelector('.lens-detail')?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}))}
function attach(id,focus=true){if(!state.tags.includes(id))state.tags.push(id);if(focus)nextTick(()=>document.querySelector('#lens-draft')?.focus({preventScroll:true}))}
function detach(id){state.tags=state.tags.filter(x=>x!==id)}
provide('lens',{state,filtered,visible,selected,related,relatedIds,setRange,select,attach,detach,jump,incident});
function change(value){current.value=typeof value==='number'?designs[(designs.findIndex(d=>d.key===current.value)+value+8)%8].key:value;const url=new URL(location.href);url.searchParams.set('variant',current.value);history.replaceState({},'',url);}
function keyboard(e){if(e.target.closest('input,textarea,select,[contenteditable]')||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();change(e.key==='ArrowRight'?1:-1)}}
watch(filtered,()=>{if(state.selectedId&&!filtered.value.some(e=>e.id===state.selectedId))state.selectedId=null;});
watch(current,()=>console.info('TRACE lens refinement',JSON.parse(JSON.stringify({variant:current.value,state}))),{immediate:true});
onMounted(()=>window.addEventListener('keydown',keyboard));onUnmounted(()=>window.removeEventListener('keydown',keyboard));
</script><template><div class="lens-study" :class="current" dir="rtl"><div class="top-scroll-fade"></div><header class="lens-appbar glass"><a class="lens-brand" href="?variant=L1">TRACE</a><div class="appbar-case"><b>תחקיר T-041</b><span>5 באוקטובר 2026</span></div><span class="appbar-simulation">נתוני הדגמה</span><details class="design-description"><summary><Info/><span>{{active.name}}</span></summary><div><b>{{active.title}}</b><p>{{active.description}}</p><a href="?variant=T7">הכיוון שנבחר: 07 ↗</a></div></details></header>
<div class="lens-workspace"><main class="lens-main"><div class="lens-page-title"><div><span>תמונת האירוע</span><h1>{{active.title}}</h1></div><div class="lens-filters"><label class="lens-search"><Search/><input v-model="state.query" aria-label="חיפוש בציר הזמן" placeholder="חיפוש רשומה"/><button v-if="state.query" @click="state.query=''" aria-label="ניקוי חיפוש"><X/></button></label><select v-model="state.target" aria-label="סינון לפי ישות"><option value="">כל הישויות</option><option v-for="t in ['T-041','T-208','T-312','T-509','ARCHIVE']" :key="t">{{t}}</option></select><button class="alerts-toggle" :class="{on:state.onlyAlerts}" :aria-pressed="state.onlyAlerts" @click="state.onlyAlerts=!state.onlyAlerts">חריגים בלבד</button></div></div>
<component :is="components[current]" :key="current"/>
</main><LensChat/></div>
<nav v-if="dev" class="lens-switcher glass" dir="ltr" aria-label="Lens design alternatives"><button @click="change(-1)" aria-label="Previous lens design"><ChevronLeft/></button><label><small>DESIGN</small><select :value="current" @change="change($event.target.value)" aria-label="Choose lens design"><option v-for="d in designs" :key="d.key" :value="d.key">{{d.key.slice(1).padStart(2,'0')}} · {{d.name}}</option></select></label><span class="design-counter">{{current.slice(1)}} / 8</span><button @click="change(1)" aria-label="Next lens design"><ChevronRight/></button><details><summary aria-label="Prototype state"><Info/></summary><div class="lens-state"><b>{{active.title}}</b><p>{{active.description}}</p><pre>{{JSON.stringify({variant:current,start:state.start,span:state.span,selected:state.selectedId,query:state.query,target:state.target,onlyAlerts:state.onlyAlerts,tags:state.tags,draft:state.draft,messages:state.messages.length},null,2)}}</pre></div></details></nav></div></template>