<script setup>
import {computed,nextTick,ref} from 'vue';import {useLens,recordsAll,clock} from './model';import {AtSign,ArrowUp,X,MessageCircle,Plus} from 'lucide-vue-next';
const {state,selected,visible,attach,detach,jump}=useLens();const composer=ref(null),messages=ref(null),picker=ref(false),query=ref('');
const suggestions=computed(()=>{const q=query.value.toLowerCase().replace('@','');const pool=q?recordsAll: [selected.value,...visible.value.filter(e=>e.severity!=='normal'),...visible.value].filter(Boolean);return [...new Map(pool.filter(e=>(e.id+' '+e.title+' '+e.target).toLowerCase().includes(q)).map(e=>[e.id,e])).values()].slice(0,8)});
function choose(id){attach(id,false);picker.value=false;query.value='';state.draft=state.draft.replace(/@[^\s@]*$/,'');nextTick(()=>composer.value?.focus())}
function mention(){picker.value=!picker.value;query.value=''}
function typed(){const match=state.draft.match(/@([^\s@]*)$/);if(match){picker.value=true;query.value=match[1]}else{picker.value=false}}
async function send(){if(!state.draft.trim()&&!state.tags.length)return;const refs=[...state.tags];state.messages.push({role:'user',text:state.draft.trim()||'בדיקת הראיות המצורפות',refs});const events=refs.map(id=>recordsAll.find(e=>e.id===id)).filter(Boolean);state.messages.push({role:'assistant',text:events.length?'צורפו '+events.length+' ראיות. '+events.map(e=>e.id+': '+e.title+' ('+clock(e.t)+')').join('; ')+'. אפשר להצליב את הזמנים והמזהים. סימון חריג או קרבה בזמן לבדם אינם הוכחת קשר סיבתי.':'זו הדגמת ממשק עם תשובות מוכנות. צרפו נקודות מציר הזמן כדי לראות כיצד הראיות עוברות לשיחה.',refs});state.draft='';state.tags=[];picker.value=false;await nextTick();messages.value?.scrollTo({top:messages.value.scrollHeight,behavior:'smooth'})}
</script><template><aside class="lens-chat glass" aria-label="עוזר תחקיר"><header><MessageCircle/><div><h2>עוזר תחקיר</h2><small>תשובות הדגמה</small></div></header>
<div class="chat-scroll" ref="messages"><div v-if="!state.messages.length" class="chat-welcome"><h3>מתחילים בראיה.</h3><p>צרפו פריט מציר הזמן, או הקלידו <kbd>@</kbd> כדי לבחור ראיות לשאלה.</p><button v-if="selected" @click="choose(selected.id)"><AtSign/>צרפו את {{selected.id}}</button></div><article v-for="(m,i) in state.messages" :key="i" :class="['lens-message',m.role]"><small>{{m.role==='user'?'אתם':'TRACE · הדגמה'}}</small><p>{{m.text}}</p><div class="message-citations"><button v-for="id in m.refs" :key="id" @click="jump(id)"><AtSign/>{{id}}</button></div></article></div>
<div class="compose-area"><div v-if="picker" class="mention-picker"><label>בחירת ראיה<input v-model="query" placeholder="מזהה, תוכן או מטרה" aria-label="חיפוש ראיה לתיוג"/></label><button v-for="e in suggestions" :key="e.id" @click="choose(e.id)"><span>{{e.title}}<small>{{e.id}} · {{clock(e.t)}}</small></span><Plus/></button><p v-if="!suggestions.length">לא נמצאו ראיות תואמות.</p><button class="close-picker" @click="picker=false">סגירה</button></div>
<div v-if="state.tags.length" class="draft-tags"><span v-for="id in state.tags" :key="id"><button @click="jump(id)"><AtSign/>{{id}}</button><button @click="detach(id)" :aria-label="'הסרת '+id"><X/></button></span></div>
<form @submit.prevent="send"><label for="lens-draft">שאלה על הראיות</label><textarea id="lens-draft" ref="composer" v-model="state.draft" rows="3" placeholder="מה כדאי לבדוק כאן? השתמשו ב־@ לתיוג" @input="typed" @keydown.ctrl.enter.prevent="send" @keydown.meta.enter.prevent="send"></textarea><div class="composer-actions"><button type="button" @click="mention" :aria-expanded="picker" aria-label="תיוג ראיה"><AtSign/></button><small>{{state.tags.length?state.tags.length+' ראיות מצורפות':'Ctrl + Enter לשליחה'}}</small><button class="send-button" :disabled="!state.draft.trim()&&!state.tags.length" aria-label="שליחת הודעה"><ArrowUp/></button></div></form><p class="session-note">נתונים מסומלצים · הטיוטה זמנית</p></div></aside></template>