import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
const page=await browser.newPage({viewport:{width:1512,height:1100},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173/?variant=original',{waitUntil:'networkidle'});
const chat=await page.locator('.chat-panel').boundingBox(), timeline=await page.locator('.timeline-panel').boundingBox();
assert.ok(chat.x>timeline.x,'Chat should be on the right');
assert.equal(await page.locator('.event-list,.event-row').count(),0);
assert.equal(await page.locator('.system-copy strong').count(),5);
await page.getByRole('button',{name:'כל האירוע',exact:true}).click();
assert.equal(await page.locator('.timeline-event').count(),15);
assert.equal(await page.locator('.timeline-event .event-caption').count(),15);
await page.getByRole('button',{name:'חריגות בלבד',exact:true}).click();
assert.equal(await page.locator('.timeline-event').count(),7);
await page.getByRole('button',{name:'חריגות בלבד',exact:true}).click();
await page.getByRole('textbox',{name:'חיפוש אירועים'}).fill('T-041');
assert.equal(await page.locator('.timeline-event').count(),8);
await page.getByRole('button',{name:'ניקוי חיפוש'}).click();
await page.locator('.timeline-event').filter({hasText:'שירות ההתרעות נעצר'}).click();
assert.match(await page.locator('.selected-summary').innerText(),/שירות ההתרעות נעצר/);
assert.match(await page.locator('.selected-timing').innerText(),/146/);
await page.getByRole('button',{name:'רשומת המקור',exact:true}).click();
assert.match(await page.locator('pre').innerText(),/PROCESS_EXIT/);
await page.getByRole('button',{name:'מיקוד באירוע',exact:true}).click();
const before=await page.locator('.time-window').innerText();
await page.getByRole('button',{name:'חלון זמן מאוחר יותר',exact:true}).click();
assert.notEqual(await page.locator('.time-window').innerText(),before);
assert.equal(await page.locator('.timeline-event.interval').filter({hasText:'שירות ההתרעות נעצר'}).count(),1,'Ongoing interval should remain visible after start leaves view');
await page.getByRole('slider',{name:'הזזת חלון הזמן'}).fill('0');
assert.match(await page.locator('.time-window').innerText(),/14:30:00/);
await page.getByRole('button',{name:'מיקוד באירוע',exact:true}).click();
await page.getByRole('button',{name:'למה לא הייתה תגובה במשך 102 שניות?',exact:true}).click();
await page.locator('.message.assistant').waitFor();
await page.locator('.message.assistant .citation').filter({hasText:'EV-107'}).click();
assert.match(await page.locator('.selected-summary').innerText(),/שירות ההתרעות נעצר/);
await page.getByRole('button',{name:'אישור מסקנה ושמירה',exact:true}).click();
await page.getByRole('button',{name:'לקחים שמורים',exact:true}).click();
assert.equal(await page.locator('.lesson').count(),1);
await page.reload();
await page.getByRole('button',{name:'לקחים שמורים',exact:true}).click();
assert.equal(await page.locator('.lesson').count(),1);
await page.getByRole('button',{name:'סביבת האירועים',exact:true}).click();
await page.getByRole('button',{name:'כל האירוע',exact:true}).click();
await page.screenshot({path:'artifacts/trace-desktop.png',fullPage:true});
await page.locator('.timeline-event').filter({hasText:'שירות ההתרעות נעצר'}).click();
await page.screenshot({path:'artifacts/trace-investigation.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'artifacts/trace-mobile.png',fullPage:true});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile document overflow');
const label=page.locator('.source-label').first();
const xBefore=(await label.boundingBox()).x;
await page.locator('.timeline-scroll').evaluate(e=>e.scrollLeft=-300);
assert.ok(Math.abs((await label.boundingBox()).x-xBefore)<2,'System names should remain fixed while scrolling');
await page.getByRole('button',{name:'הסתרת צ׳אט',exact:true}).click();
await page.getByRole('button',{name:'פתיחת הצ׳אט',exact:true}).click();
assert.equal(await page.locator('.chat-panel').count(),1);
assert.deepEqual(errors,[]);
console.log('PASS: right-side chat; clear system headers; no event list; labeled points; interval selection and clipping; pan, zoom and slider; filters; citations; raw evidence; saved lessons; mobile overflow and sticky system column. No browser errors.');
} finally { await browser.close(); }
