<script setup>
// THROWAWAY: ten timeline approaches on the existing route, ?variant=T1..T10.
// Question: which representation supports independent discovery at scale and precise evidence drill-down?
import {computed,defineAsyncComponent,nextTick,onMounted,onUnmounted,provide,reactive,ref,watch} from 'vue';
import {sources,recordsAll,options,DURATION,INCIDENT,clock,duration} from './data';
const components={T1:defineAsyncComponent(()=>import('./Timeline01.vue')),T2:defineAsyncComponent(()=>import('./Timeline02.vue')),T3:defineAsyncComponent(()=>import('./Timeline03.vue')),T4:defineAsyncComponent(()=>import('./Timeline04.vue')),T5:defineAsyncComponent(()=>import('./Timeline05.vue')),T6:defineAsyncComponent(()=>import('./Timeline06.vue')),T7:defineAsyncComponent(()=>import('./Timeline07.vue')),T8:defineAsyncComponent(()=>import('./Timeline08.vue')),T9:defineAsyncComponent(()=>import('./Timeline09.vue')),T10:defineAsyncComponent(()=>import('./Timeline10.vue'))};
const initial=new URLSearchParams(location.search).get('variant')?.toUpperCase();
const current=ref(options.some(o=>o.key===initial)?initial:'T1');
const state=reactive({start:0,end:DURATION,source:'',target:'',query:'',anomalies:false,selected:null,drill:null,messages:[],notes:[],page:0,lensStart:INCIDENT-60});
const active=computed(()=>options.find(o=>o.key===current.value));
const filtered=computed(()=>{const q=state.query.trim().toLowerCase();return recordsAll.filter(e=>(!state.source||e.source===state.source)&&(!state.target||e.target===state.target)&&(!state.anomalies||e.severity!=='normal')&&(!q||[e.id,e.title,e.target,e.detail,e.raw?.message_id].join(' ').toLowerCase().includes(q)))});
const inWindow=computed(()=>filtered.value.filter(e=>e.t<state.end&&(e.end??e.t)>=state.start));
const drillRecords=computed(()=>{const d=state.drill;if(!d)return [];return filtered.value.filter(e=>e.t<d.end&&(e.end??e.t)>=d.start&&(!d.source||e.source===d.source)&&(!d.target||e.target===d.target))});
const pageRecords=computed(()=>drillRecords.value.slice(state.page*12,state.page*12+12));
const related=computed(()=>state.selected?recordsAll.filter(e=>e.id!==state.selected.id&&(state.selected.raw?.message_id?e.raw?.message_id===state.selected.raw.message_id:e.target===state.selected.target&&Math.abs(e.t-state.selected.t)<120)).slice(0,8):[]);
function setWindow(start,end){const width=Math.min(DURATION,Math.max(15,end-start));state.start=Math.max(0,Math.min(DURATION-width,start));state.end=state.start+width;}
function pan(delta){setWindow(state.start+delta,state.end+delta)}
function zoom(factor){const mid=(state.start+state.end)/2;const width=(state.end-state.start)*factor;setWindow(mid-width/2,mid+width/2)}
function inspect(start,end,extra={}){state.drill={start,end,...extra};state.page=0;state.selected=null;nextTick(()=>document.querySelector('.drill-panel')?.scrollIntoView({block:'nearest',behavior:'smooth'}));}
function select(id){const e=recordsAll.find(e=>e.id===id);if(!e)return;state.selected=e;nextTick(()=>document.querySelector('.evidence-panel')?.scrollIntoView({block:'nearest',behavior:'smooth'}));}
function jump(id){const e=recordsAll.find(e=>e.id===id);if(!e)return;state.source='';state.target='';state.query='';state.anomalies=false;state.lensStart=Math.max(0,Math.min(DURATION-300,e.t-60));setWindow(e.t-60,e.t+180);state.drill=null;nextTick(()=>select(id));}
function reset(){state.source='';state.target='';state.query='';state.anomalies=false;state.lensStart=INCIDENT-60;setWindow(0,DURATION);state.drill=null;state.selected=null;}
provide('timeline',{state,filtered,select,inspect,setWindow});
function change(key){current.value=typeof key==='number'?options[(options.findIndex(o=>o.key===current.value)+key+10)%10].key:key;const url=new URL(location.href);url.searchParams.set('variant',current.value);history.replaceState({},'',url);}
function keyboard(e){if(e.target.closest('input,textarea,select,[contenteditable],[role="slider"]')||e.ctrlKey||e.altKey||e.metaKey)return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();change(e.key==='ArrowRight'?1:-1)}}
const dev=import.meta.env.DEV;const input=ref('');const chatBody=ref(null);
function ask(q=input.value){if(!q.trim())return;state.messages.push({role:'user',text:q});const e=state.selected;state.messages.push({role:'assistant',text:e?'הראיה שנבחרה: '+e.title+'. '+e.detail+' אפשר לבדוק את רשומת המקור ולבחון האם הסדר הזמני מספיק לתמוך בהשערה.':'בתרחיש המדומה, קוד 7500 נקלט ב־14:32:00. שירות ההתרעות נעצר שנייה אחר כך; פעולה מתועדת ל־T-041 מופיעה אחרי 102 שניות. אלו נקודות פתיחה לבדיקה. סמיכות בזמן לבדה אינה מוכיחה סיבה.',refs:e?[e.id]:['EV-106','EV-107','EV-111']});input.value='';setTimeout(()=>chatBody.value?.scrollTo({top:chatBody.value.scrollHeight,behavior:'smooth'}),0);}
const observation=ref('');
function pin(){if(!observation.value.trim())return;state.notes.push({text:observation.value,evidence:state.selected?.id??null});observation.value=''}
watch(current,()=>console.info('TRACE timeline study',JSON.parse(JSON.stringify({variant:current.value,state}))),{immediate:true});
watch([()=>state.source,()=>state.target,()=>state.query,()=>state.anomalies],()=>{state.page=0;state.selected=null});
onMounted(()=>window.addEventListener('keydown',keyboard));onUnmounted(()=>window.removeEventListener('keydown',keyboard));
</script>
<template><div class="timeline-study" dir="rtl">
<header class="study-header"><a class="trace-brand" href="?variant=T1">TRACE<span>חקירת אירוע</span></a><div class="case-header"><b>T-041</b><span>05.10.2026 · 08:00–24:00</span><span>{{recordsAll.length.toLocaleString()}} רשומות · 5 מערכות</span></div><span class="demo-tag">מחקר UI · נתונים מדומים</span></header>
<div class="study-workspace">
<main class="timeline-main">
<div class="view-heading"><div><span class="eyebrow">TIMELINE EXPLORATION / {{current.slice(1).padStart(2,'0')}}</span><h1>{{active.title}}</h1><p>{{active.question}}</p></div><button class="quiet-button" @click="reset">איפוס התצוגה ↺</button></div>
<div class="filter-bar"><label class="search-label"><span>חיפוש</span><input v-model="state.query" placeholder="מזהה, הודעה או תוכן…" /></label><label>מערכת<select v-model="state.source"><option value="">כל המערכות</option><option v-for="s in sources" :key="s.id" :value="s.id">{{s.label}}</option></select></label><label>ישות<select v-model="state.target"><option value="">כל הישויות</option><option v-for="t in ['T-041','T-208','T-312','T-509','ARCHIVE','SENSOR-A']" :key="t">{{t}}</option></select></label><label class="checkbox-label"><input v-model="state.anomalies" type="checkbox"/> חריגות בלבד</label></div>
<div v-if="!['T7','T8','T10'].includes(current)" class="time-toolbar"><div class="range-title"><b dir="ltr">{{clock(state.start)}} — {{clock(state.end)}}</b><small>{{duration(state.end-state.start)}} · {{inWindow.length.toLocaleString()}} רשומות בחלון · {{filtered.length.toLocaleString()}} אחרי סינון</small></div><div class="time-controls"><button @click="setWindow(0,DURATION)">יום מלא</button><button @click="setWindow(INCIDENT-600,INCIDENT+1200)">30 דקות</button><button class="accent-button" @click="setWindow(INCIDENT-30,INCIDENT+150)">חלון האירוע</button><button aria-label="הזזה אחורה" @click="pan(-(state.end-state.start)/2)">←</button><button aria-label="זום פנימה" @click="zoom(.5)">＋</button><button aria-label="זום החוצה" @click="zoom(2)">−</button><button aria-label="הזזה קדימה" @click="pan((state.end-state.start)/2)">→</button></div></div>
<div v-if="!['T7','T8','T10'].includes(current)" class="range-slider"><input type="range" aria-label="הזזת חלון הזמן" :min="0" :max="Math.max(0,DURATION-(state.end-state.start))" :disabled="state.end-state.start===DURATION" :value="state.start" @input="setWindow(Number($event.target.value),Number($event.target.value)+state.end-state.start)" /><span>תחילת יום</span><span>סוף יום</span></div>
<p v-if="['T7','T8','T10'].includes(current)" class="independent-window">{{filtered.length.toLocaleString()}} רשומות אחרי סינון · בחירת הזמן נמצאת בתוך התצוגה</p><section class="timeline-canvas" :aria-label="active.name"><div class="canvas-intro"><p>{{active.hint}}</p><span>זמן →</span></div><component :is="components[current]" :key="current"/></section>
<div class="view-footer"><span><i class="legend-dot"></i> פעילות רגילה</span><span><i class="legend-dot anomaly"></i> חריגה מהמקור</span><span>לחיצה פותחת ראיות ↓</span><details><summary>מתי התצוגה שימושית?</summary><p>{{active.tradeoff}}</p></details></div>
<section v-if="state.drill" class="drill-panel"><header><div><span class="eyebrow">חלון שנבחר</span><h2 dir="ltr">{{clock(state.drill.start)}} — {{clock(state.drill.end)}}</h2><small>{{drillRecords.length.toLocaleString()}} רשומות {{state.drill.source?' · '+sources.find(s=>s.id===state.drill.source)?.label:''}} {{state.drill.target?' · '+state.drill.target:''}}</small></div><div><button @click="setWindow(state.drill.start,state.drill.end); if(['T7','T8','T10'].includes(current)) change('T1')">הגדלת החלון בציר ↗</button><button aria-label="סגירת חלון רשומות" @click="state.drill=null">×</button></div></header>
<div v-if="state.drill.note" class="drill-context"><p>{{state.drill.note}}</p><button v-for="id in state.drill.refs" :key="id" @click="select(id)">{{id}} ↗</button></div><p v-if="!drillRecords.length" class="empty">אין רשומות תחת המסננים הנוכחיים. היעדר נתונים אינו מוכיח שלא התרחשה פעילות.</p>
<div class="drill-records"><button v-for="e in pageRecords" :key="e.id" class="record-row" :class="{selected:state.selected?.id===e.id,alert:e.severity!=='normal'}" @click="select(e.id)"><time>{{clock(e.t)}}</time><span>{{e.title}}<small>{{sources.find(s=>s.id===e.source)?.label}} · {{e.target}}{{e.end?' · '+duration(e.end-e.t):''}}{{e.soft?' · זמן מיוחס':''}}</small></span><b>↗</b></button></div>
<div v-if="drillRecords.length>12" class="pagination"><button :disabled="!state.page" @click="state.page--">הקודם</button><span>{{state.page*12+1}}–{{Math.min(drillRecords.length,(state.page+1)*12)}} מתוך {{drillRecords.length}}</span><button :disabled="(state.page+1)*12>=drillRecords.length" @click="state.page++">הבא</button></div></section>
<section v-if="state.selected" class="evidence-panel"><header><div><span class="eyebrow">ראיית מקור · {{state.selected.id}}</span><h2>{{state.selected.title}}</h2><p>{{sources.find(s=>s.id===state.selected.source)?.label}} · {{state.selected.target}} · <b dir="ltr">{{clock(state.selected.t)}}{{state.selected.end?' — '+clock(state.selected.end):''}}</b><span v-if="state.selected.soft"> · קול / זמן מיוחס / ודאות בינונית</span></p></div><button aria-label="סגירת ראיה" @click="state.selected=null">×</button></header><p>{{state.selected.detail}}</p><div class="evidence-actions"><button @click="ask('בחן את הראיה '+state.selected.id)">בדיקה עם הסוכן ↗</button><details><summary>רשומת מקור</summary><pre dir="ltr">{{JSON.stringify(state.selected.raw||{event_id:state.selected.id,timestamp:clock(state.selected.t),source:state.selected.source,target:state.selected.target},null,2)}}</pre></details></div><div v-if="related.length" class="related-evidence"><span>{{state.selected.raw?.message_id?'אותו מזהה הודעה':'אותה ישות בטווח ±2 דקות'}}:</span><button v-for="e in related" :key="e.id" @click="select(e.id)">{{e.id}}</button></div></section>
<div v-if="!state.drill&&!state.selected" class="inspection-empty"><span>↗</span><div><b>מבט רחב קודם. ראיה מדויקת כשצריך.</b><p>בחרו מקבץ, אינטרוול או אירוע בתצוגה כדי לבדוק מה עומד מאחוריו.</p></div></div>
<form class="observation" @submit.prevent="pin"><label for="observation">התצפית שלכם</label><input id="observation" v-model="observation" placeholder="דפוס שזיהיתם, שאלה או השערה לבדיקה…" /><button :disabled="!observation.trim()">שמירה למפגש +</button></form><div v-for="(n,i) in state.notes" :key="i" class="saved-note"><span>תצפית {{i+1}} · אינה מסקנה מאומתת</span><p>{{n.text}}</p><button v-if="n.evidence" @click="jump(n.evidence)">{{n.evidence}} ↗</button></div>
</main>
<aside class="timeline-chat"><header><div><span class="assistant-symbol">✳</span><b>עוזר התחקיר</b></div><small>תשובות מוכנות להמחשה</small></header><div ref="chatBody" class="timeline-messages"><div v-if="!state.messages.length" class="assistant-intro"><span class="eyebrow">מסתכלים יחד</span><h2>מה אתם רואים<br>בציר הזמן?</h2><p>בדקו דפוסים בעצמכם, ופתחו את הראיות לפני גיבוש מסקנה.</p><button @click="ask('מה השתנה לפני תגובת המפעיל?')">מה השתנה לפני תגובת המפעיל? ↗</button></div><article v-for="(m,i) in state.messages" :key="i" :class="['message',m.role]"><small>{{m.role==='user'?'אתם':'TRACE · הדגמה'}}</small><p>{{m.text}}</p><div><button v-for="id in m.refs" :key="id" @click="jump(id)">{{id}} ↗</button></div></article></div><div v-if="state.selected" class="chat-context">בהקשר: {{state.selected.id}} · {{state.selected.title}}</div><form class="timeline-chat-form" @submit.prevent="ask()"><textarea v-model="input" aria-label="שאלה לעוזר התחקיר" placeholder="שאלה על הראיות…" rows="2"></textarea><button :disabled="!input.trim()" aria-label="שליחת שאלה">↑</button></form><small class="chat-disclaimer">הסוכן והנתונים מדומים · הערות נשמרות במפגש בלבד</small></aside>
</div>
<nav v-if="dev" class="timeline-switcher" dir="ltr" aria-label="Timeline alternatives"><button @click="change(-1)" aria-label="Previous timeline">←</button><span class="switcher-label">TIMELINES</span><button v-for="o in options" :key="o.key" :class="{chosen:current===o.key}" :title="o.name+' · '+o.title" :aria-label="o.key+' '+o.name" :aria-pressed="current===o.key" @click="change(o.key)">{{o.key.slice(1).padStart(2,'0')}}</button><button @click="change(1)" aria-label="Next timeline">→</button><details class="study-state"><summary aria-label="Prototype state">ⓘ</summary><div><b>{{current}} · {{active.name}}</b><p>{{active.tradeoff}}</p><pre>{{JSON.stringify({range:[state.start,state.end],source:state.source,target:state.target,query:state.query,anomalies:state.anomalies,selected:state.selected?.id,drill:state.drill,notes:state.notes.length,messages:state.messages.length},null,2)}}</pre><a href="?variant=A">Previous layout study ↗</a></div></details></nav>
</div></template>